services:
  frontend:
    image: ghcr.io/worklenz/worklenz-frontend
    build:
      context: ./worklenz-frontend
      dockerfile: Dockerfile
    container_name: worklenz_frontend
    ports:
      - "4200:4200"
    depends_on:
      backend:
        condition: service_started
    networks:
      - worklenz    

  backend:
    image: ghcr.io/worklenz/worklenz-backend
    build:
      context: ./worklenz-backend
      dockerfile: Dockerfile
    container_name: worklenz_backend
    ports:
      - "3000:3000"
    environment:
      - ANGULAR_DIST_DIR
      - ANGULAR_SRC_DIR
      - AWS_REGION
      - BACKEND_PUBLIC_DIR
      - BACKEND_VIEWS_DIR
      - COMMIT_BUILD_IMMEDIATELY
      - COOKIE_SECRET
      - DB_HOST
      - DB_MAX_CLIENTS
      - DB_NAME
      - DB_PASSWORD
      - DB_PORT
      - DB_USER
      - GOOGLE_CALLBACK_URL
      - GOOGLE_CLIENT_ID
      - GOOGLE_CLIENT_SECRET
      - HOSTNAME
      - LOGIN_FAILURE_REDIRECT
      - NODE_ENV
      - PORT
      - SESSION_NAME
      - SESSION_SECRET
      - SLACK_WEBHOOK
      - SOCKET_IO_CORS
      - SOURCE_EMAIL
      - USE_PG_NATIVE
      - BUCKET
      - REGION
    networks:
      - worklenz

volumes:
  worklenz_postgres_data:

networks:
  worklenz: